# Generated by Django 4.0.5 on 2022-06-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mango_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mango',
            name='mango_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangos', to='api.mango_shop'),
        ),
    ]
